### ISSUE TITLE
Criar postagem do doador - Figma

### ISSUE THREAD

**Issue by LuizLLPz** [LuizLLPz/Grupo-8#1]

**Comment by LuizLLPz** [comment]
![image](https://user-images.githubusercontent.com/80237227/168587271-cd62881e-98ca-47b5-9c71-6b79001f3fea.png)

**Comment by vitorbiqua** [comment]
![image](https://user-images.githubusercontent.com/66045368/168602249-199e98c1-348b-4802-a2d4-87c4834a638c.png)

Imagem do card do anúncio - 1° versão (mobile)

![image](https://user-images.githubusercontent.com/66045368/168602805-4815b7e1-c8c1-45ec-9b2e-8bd9a6c4f264.png)

Imagem do card do anúncio - 1° versão (desktop)
